[2025-04-20T06:38:53.160+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_stg_to_dwh_to_mart.run_training_etl_function manual__2025-04-20T06:38:32.443251+00:00 [queued]>
[2025-04-20T06:38:53.176+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_stg_to_dwh_to_mart.run_training_etl_function manual__2025-04-20T06:38:32.443251+00:00 [queued]>
[2025-04-20T06:38:53.177+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 1
[2025-04-20T06:38:53.205+0000] {taskinstance.py:2217} INFO - Executing <Task(PythonOperator): run_training_etl_function> on 2025-04-20 06:38:32.443251+00:00
[2025-04-20T06:38:53.213+0000] {standard_task_runner.py:60} INFO - Started process 296 to run task
[2025-04-20T06:38:53.218+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'etl_stg_to_dwh_to_mart', 'run_training_etl_function', 'manual__2025-04-20T06:38:32.443251+00:00', '--job-id', '11', '--raw', '--subdir', 'DAGS_FOLDER/main_etl.py', '--cfg-path', '/tmp/tmpckk5_e3m']
[2025-04-20T06:38:53.221+0000] {standard_task_runner.py:88} INFO - Job 11: Subtask run_training_etl_function
[2025-04-20T06:38:53.291+0000] {task_command.py:423} INFO - Running <TaskInstance: etl_stg_to_dwh_to_mart.run_training_etl_function manual__2025-04-20T06:38:32.443251+00:00 [running]> on host d53bd6ff311d
[2025-04-20T06:38:53.424+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='etl_stg_to_dwh_to_mart' AIRFLOW_CTX_TASK_ID='run_training_etl_function' AIRFLOW_CTX_EXECUTION_DATE='2025-04-20T06:38:32.443251+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-04-20T06:38:32.443251+00:00'
[2025-04-20T06:38:53.453+0000] {mart_report.py:55} INFO - Creating materialized view: mart.mv_most_diagnose
[2025-04-20T06:38:53.459+0000] {mart_report.py:60} ERROR - Error handling MV mv_most_diagnose: (psycopg2.errors.DuplicateTable) relation "mv_most_diagnose" already exists

[SQL: CREATE MATERIALIZED VIEW mv_most_diagnose AS
SELECT 
    remark as category,
    COUNT(*) AS total_tercatat
FROM model.dim_condition where remark != ''
GROUP BY remark
ORDER BY total_tercatat DESC;]
(Background on this error at: https://sqlalche.me/e/14/f405)
[2025-04-20T06:38:53.463+0000] {mart_report.py:55} INFO - Creating materialized view: mart.mv_segmentation_patient
[2025-04-20T06:38:53.501+0000] {mart_report.py:58} INFO - Materialized view mart.mv_segmentation_patient created successfully.
[2025-04-20T06:38:53.507+0000] {mart_report.py:55} INFO - Creating materialized view: mart.mv_patient_claim
[2025-04-20T06:38:53.525+0000] {mart_report.py:58} INFO - Materialized view mart.mv_patient_claim created successfully.
[2025-04-20T06:38:53.530+0000] {mart_report.py:55} INFO - Creating materialized view: mart.mv_encounter_history
[2025-04-20T06:38:53.550+0000] {mart_report.py:58} INFO - Materialized view mart.mv_encounter_history created successfully.
[2025-04-20T06:38:53.551+0000] {mart_report.py:74} INFO - Process Completed Successfully!
[2025-04-20T06:38:53.552+0000] {python.py:202} INFO - Done. Returned value was: None
[2025-04-20T06:38:53.566+0000] {taskinstance.py:1149} INFO - Marking task as SUCCESS. dag_id=etl_stg_to_dwh_to_mart, task_id=run_training_etl_function, execution_date=20250420T063832, start_date=20250420T063853, end_date=20250420T063853
[2025-04-20T06:38:53.631+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2025-04-20T06:38:53.663+0000] {taskinstance.py:3312} INFO - 0 downstream tasks scheduled from follow-on schedule check
